require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Max: 200

CyclomaticComplexity:
  Enabled: false

PerceivedComplexity:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/FilePath:
  Enabled: false

convention:Metrics/BlockLength:
  Max: 70

RSpec/MultipleExpectations:
  Max: 100

RSpec/ExampleLength:
  Max: 100

RSpec/FilePath:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false